### ISSUE TITLE
Design main page

### ISSUE THREAD

**Issue by Maria-Osiak** [Maria-Osiak/FoodDice#2]
Give color and nice design to main page. Don't just have grey colors.

- [x] Colored background
- [x] Menu-button and icon
- [x] Buttons in menu
- [x] Dice-instruction
- [x] Flexible layout

**Comment by GlennJoakimB** [comment]
Ser vel greit ut dette her?
mangler burger-meny til meny-knappen, og terningen mangler

![image](https://user-images.githubusercontent.com/89195051/144843123-1214116d-dce4-4452-80f2-25767b058c18.png)

Har ikkje pushet dette opp enda
